os: linux
dist: xenial

language: python
python:
  - 3.6
  - 3.7
  - 3.8
cache:
  pip: true

before_install:
  - pip install -r requirements_all.txt
  - pip install -e .
install:
  - python setup.py install
  - python setup.py sdist
before_script:
  - pylint src tests
  - black --check --fast .
script:
  - py.test

deploy:
  - provider: pypi
    user: $pypi_test_user
    password: $pypi_test_pass
    server: $pypi_test
    on:
      branch: deploy-test
      python: 3.8
  - provider: pypi
    user: $pypi_user
    password: $pypi_pass
    server: $pypi
    on:
      branch: deploy
      python: 3.8
