# -*- coding: utf-8 -*-
"""DSM 6 SYNO.SurveillanceStation.Camera data."""

DSM_6_SURVEILLANCE_STATION_CAMERA_LIST = {
    "data": {
        "cameras": [
            {
                "ADCap": 0,
                "AppList": [],
                "DINum": 0,
                "DONum": 0,
                "MDCap": 0,
                "MDModeList": [0, 1],
                "PDCap": 0,
                "PDDepend": 0,
                "TDCap": 0,
                "advLiveMinDuration": 10,
                "advLiveProfile": 1,
                "advLiveTrigAuto": False,
                "advLiveTrigEvt": "10000000000000000000000000000000000000000000000000000000000000000000000000000000",
                "advLiveTrigSingle": True,
                "analyticsType": 0,
                "application": False,
                "audioCap": False,
                "audioOut": False,
                "audioType": 6,
                "autoFocus": False,
                "autoPan": 0,
                "auto_restart_interval": 0,
                "blAudioDisableRec": False,
                "blAudioPriv": True,
                "blDisableRec": False,
                "blEnableExtDI": False,
                "blEnableLiveBuffering": False,
                "blG726LE": False,
                "blLiveviewPriv": True,
                "blPresetSpeed": False,
                "blPtzShowIcon": False,
                "blReceivePocZero": False,
                "blThirdStream": True,
                "calling_notify_ado_src_id": 0,
                "calling_notify_duration": 0,
                "camIdOnRecServer": 0,
                "camLiveMode": 0,
                "camMobileLiveMode": 0,
                "camMountType": 0,
                "camRecShare": "surveillance",
                "camRecShareMountType": 0,
                "camRecSharePath": "/volume1/surveillance",
                "camRecStorageStatus": 0,
                "camRecVolume": "/volume1",
                "camRotOption": 0,
                "camStatus": 1,
                "channel_id": "1",
                "daybegin": 8,
                "dayend": 18,
                "defLiveProfile": 1,
                "deleted": False,
                "detailInfo": {
                    "advContMinDuration": 10,
                    "advContTrigEvt": "10000000000000000000000000000000000000000000000000000000000000000000000000000000",
                    "advLiveMinDuration": 10,
                    "advLiveTrigAuto": False,
                    "advLiveTrigEvt": "10000000000000000000000000000000000000000000000000000000000000000000000000000000",
                    "advLiveTrigSingle": True,
                    "blAudioDisableRec": False,
                    "blDisableRec": False,
                    "blEnableExtDI": False,
                    "blThirdStreamProfile": True,
                    "camApplyCodecOptimization": False,
                    "camApplyKeyFrameInterval": False,
                    "camAudioType": 6,
                    "camChannel": "1",
                    "camCodecOptimization": "",
                    "camDeviceType": 1,
                    "camDynamicFps": False,
                    "camDynamicGop": False,
                    "camFirmware": "",
                    "camFolder": "Camera1",
                    "camFov": "",
                    "camFps": "",
                    "camIP": "192.168.1.101",
                    "camIsRotByDate": True,
                    "camIsRotBySpace": False,
                    "camIsSetEvtPrefix": False,
                    "camIsSetRecFolder": False,
                    "camKeyFrameInterval": -1,
                    "camLastKeyFrameInterval": -1,
                    "camLiveAvgBitrate": 1000,
                    "camLiveBitrateCtrl": 0,
                    "camLiveCbrBitrate": 1000,
                    "camLiveFps": "",
                    "camLiveMode": 0,
                    "camLiveQuality": "",
                    "camLiveResolution": "1920x1080",
                    "camLiveSmartBitrateCtrl": 0,
                    "camLiveStreamNo": 0,
                    "camMobileAvgBitrate": 1000,
                    "camMobileBitrateCtrl": 0,
                    "camMobileCbrBitrate": 1000,
                    "camMobileFps": "",
                    "camMobileLiveMode": 0,
                    "camMobileQuality": "",
                    "camMobileResolution": "1920x1080",
                    "camMobileSmartBitrateCtrl": 0,
                    "camMobileStreamNo": 0,
                    "camModel": "",
                    "camMountType": 0,
                    "camName": "Camera1",
                    "camPassWord": "＃＃＃＃＃＃＃＃",
                    "camPort": 554,
                    "camPostRecTime": 5,
                    "camPreRecTime": 5,
                    "camPrefix": "Camera1",
                    "camQuality": "",
                    "camRecAvgBitrate": 1000,
                    "camRecBitrateCtrl": 0,
                    "camRecCbrBitrate": 1000,
                    "camRecShare": "surveillance",
                    "camRecSharePath": "/volume1/surveillance",
                    "camRecSmartBitrateCtrl": 0,
                    "camRecStorageStatus": 0,
                    "camRecStreamNo": 0,
                    "camRecTime": 30,
                    "camResolution": "1920x1080",
                    "camRotByDate": 30,
                    "camRotBySpace": 10,
                    "camRotOption": 0,
                    "camRtspKeepAlive": 1,
                    "camRtspProtocol": 4,
                    "camSchedule": [
                        [
                            1,
                            1,
                            1,
                            1,
                            1,
                            1,
                            1,
                            1,
                            1,
                            1,
                            1,
                            1,
                            1,
                            1,
                            1,
                            1,
                            1,
                            1,
                            1,
                            1,
                            1,
                            1,
                            1,
                            1,
                            1,
                            1,
                            1,
                            1,
                            1,
                            1,
                            1,
                            1,
                            1,
                            1,
                            1,
                            1,
                            1,
                            1,
                            1,
                            1,
                            1,
                            1,
                            1,
                            1,
                            1,
                            1,
                            1,
                            1,
                        ],
                        [
                            1,
                            1,
                            1,
                            1,
                            1,
                            1,
                            1,
                            1,
                            1,
                            1,
                            1,
                            1,
                            1,
                            1,
                            1,
                            1,
                            1,
                            1,
                            1,
                            1,
                            1,
                            1,
                            1,
                            1,
                            1,
                            1,
                            1,
                            1,
                            1,
                            1,
                            1,
                            1,
                            1,
                            1,
                            1,
                            1,
                            1,
                            1,
                            1,
                            1,
                            1,
                            1,
                            1,
                            1,
                            1,
                            1,
                            1,
                            1,
                        ],
                        [
                            1,
                            1,
                            1,
                            1,
                            1,
                            1,
                            1,
                            1,
                            1,
                            1,
                            1,
                            1,
                            1,
                            1,
                            1,
                            1,
                            1,
                            1,
                            1,
                            1,
                            1,
                            1,
                            1,
                            1,
                            1,
                            1,
                            1,
                            1,
                            1,
                            1,
                            1,
                            1,
                            1,
                            1,
                            1,
                            1,
                            1,
                            1,
                            1,
                            1,
                            1,
                            1,
                            1,
                            1,
                            1,
                            1,
                            1,
                            1,
                        ],
                        [
                            1,
                            1,
                            1,
                            1,
                            1,
                            1,
                            1,
                            1,
                            1,
                            1,
                            1,
                            1,
                            1,
                            1,
                            1,
                            1,
                            1,
                            1,
                            1,
                            1,
                            1,
                            1,
                            1,
                            1,
                            1,
                            1,
                            1,
                            1,
                            1,
                            1,
                            1,
                            1,
                            1,
                            1,
                            1,
                            1,
                            1,
                            1,
                            1,
                            1,
                            1,
                            1,
                            1,
                            1,
                            1,
                            1,
                            1,
                            1,
                        ],
                        [
                            1,
                            1,
                            1,
                            1,
                            1,
                            1,
                            1,
                            1,
                            1,
                            1,
                            1,
                            1,
                            1,
                            1,
                            1,
                            1,
                            1,
                            1,
                            1,
                            1,
                            1,
                            1,
                            1,
                            1,
                            1,
                            1,
                            1,
                            1,
                            1,
                            1,
                            1,
                            1,
                            1,
                            1,
                            1,
                            1,
                            1,
                            1,
                            1,
                            1,
                            1,
                            1,
                            1,
                            1,
                            1,
                            1,
                            1,
                            1,
                        ],
                        [
                            1,
                            1,
                            1,
                            1,
                            1,
                            1,
                            1,
                            1,
                            1,
                            1,
                            1,
                            1,
                            1,
                            1,
                            1,
                            1,
                            1,
                            1,
                            1,
                            1,
                            1,
                            1,
                            1,
                            1,
                            1,
                            1,
                            1,
                            1,
                            1,
                            1,
                            1,
                            1,
                            1,
                            1,
                            1,
                            1,
                            1,
                            1,
                            1,
                            1,
                            1,
                            1,
                            1,
                            1,
                            1,
                            1,
                            1,
                            1,
                        ],
                        [
                            1,
                            1,
                            1,
                            1,
                            1,
                            1,
                            1,
                            1,
                            1,
                            1,
                            1,
                            1,
                            1,
                            1,
                            1,
                            1,
                            1,
                            1,
                            1,
                            1,
                            1,
                            1,
                            1,
                            1,
                            1,
                            1,
                            1,
                            1,
                            1,
                            1,
                            1,
                            1,
                            1,
                            1,
                            1,
                            1,
                            1,
                            1,
                            1,
                            1,
                            1,
                            1,
                            1,
                            1,
                            1,
                            1,
                            1,
                            1,
                        ],
                    ],
                    "camServer": 0,
                    "camSourcePath": "/live",
                    "camSourceType": 1,
                    "camTvStandard": 0,
                    "camUserName": "cam1",
                    "camVendor": "User Define",
                    "camVideoMode": "",
                    "camVideoType": "H.264",
                    "custom1DIDetect": 0,
                    "custom1Detect": 1,
                    "custom2DIDetect": 0,
                    "custom2Detect": 1,
                    "edgeStgDownloadSch": [
                        [
                            1,
                            1,
                            1,
                            1,
                            1,
                            1,
                            1,
                            1,
                            1,
                            1,
                            1,
                            1,
                            1,
                            1,
                            1,
                            1,
                            1,
                            1,
                            1,
                            1,
                            1,
                            1,
                            1,
                            1,
                            1,
                            1,
                            1,
                            1,
                            1,
                            1,
                            1,
                            1,
                            1,
                            1,
                            1,
                            1,
                            1,
                            1,
                            1,
                            1,
                            1,
                            1,
                            1,
                            1,
                            1,
                            1,
                            1,
                            1,
                        ],
                        [
                            1,
                            1,
                            1,
                            1,
                            1,
                            1,
                            1,
                            1,
                            1,
                            1,
                            1,
                            1,
                            1,
                            1,
                            1,
                            1,
                            1,
                            1,
                            1,
                            1,
                            1,
                            1,
                            1,
                            1,
                            1,
                            1,
                            1,
                            1,
                            1,
                            1,
                            1,
                            1,
                            1,
                            1,
                            1,
                            1,
                            1,
                            1,
                            1,
                            1,
                            1,
                            1,
                            1,
                            1,
                            1,
                            1,
                            1,
                            1,
                        ],
                        [
                            1,
                            1,
                            1,
                            1,
                            1,
                            1,
                            1,
                            1,
                            1,
                            1,
                            1,
                            1,
                            1,
                            1,
                            1,
                            1,
                            1,
                            1,
                            1,
                            1,
                            1,
                            1,
                            1,
                            1,
                            1,
                            1,
                            1,
                            1,
                            1,
                            1,
                            1,
                            1,
                            1,
                            1,
                            1,
                            1,
                            1,
                            1,
                            1,
                            1,
                            1,
                            1,
                            1,
                            1,
                            1,
                            1,
                            1,
                            1,
                        ],
                        [
                            1,
                            1,
                            1,
                            1,
                            1,
                            1,
                            1,
                            1,
                            1,
                            1,
                            1,
                            1,
                            1,
                            1,
                            1,
                            1,
                            1,
                            1,
                            1,
                            1,
                            1,
                            1,
                            1,
                            1,
                            1,
                            1,
                            1,
                            1,
                            1,
                            1,
                            1,
                            1,
                            1,
                            1,
                            1,
                            1,
                            1,
                            1,
                            1,
                            1,
                            1,
                            1,
                            1,
                            1,
                            1,
                            1,
                            1,
                            1,
                        ],
                        [
                            1,
                            1,
                            1,
                            1,
                            1,
                            1,
                            1,
                            1,
                            1,
                            1,
                            1,
                            1,
                            1,
                            1,
                            1,
                            1,
                            1,
                            1,
                            1,
                            1,
                            1,
                            1,
                            1,
                            1,
                            1,
                            1,
                            1,
                            1,
                            1,
                            1,
                            1,
                            1,
                            1,
                            1,
                            1,
                            1,
                            1,
                            1,
                            1,
                            1,
                            1,
                            1,
                            1,
                            1,
                            1,
                            1,
                            1,
                            1,
                        ],
                        [
                            1,
                            1,
                            1,
                            1,
                            1,
                            1,
                            1,
                            1,
                            1,
                            1,
                            1,
                            1,
                            1,
                            1,
                            1,
                            1,
                            1,
                            1,
                            1,
                            1,
                            1,
                            1,
                            1,
                            1,
                            1,
                            1,
                            1,
                            1,
                            1,
                            1,
                            1,
                            1,
                            1,
                            1,
                            1,
                            1,
                            1,
                            1,
                            1,
                            1,
                            1,
                            1,
                            1,
                            1,
                            1,
                            1,
                            1,
                            1,
                        ],
                        [
                            1,
                            1,
                            1,
                            1,
                            1,
                            1,
                            1,
                            1,
                            1,
                            1,
                            1,
                            1,
                            1,
                            1,
                            1,
                            1,
                            1,
                            1,
                            1,
                            1,
                            1,
                            1,
                            1,
                            1,
                            1,
                            1,
                            1,
                            1,
                            1,
                            1,
                            1,
                            1,
                            1,
                            1,
                            1,
                            1,
                            1,
                            1,
                            1,
                            1,
                            1,
                            1,
                            1,
                            1,
                            1,
                            1,
                            1,
                            1,
                        ],
                    ],
                    "edgeStgEnabled": False,
                    "edgeStgPostRecTime": 5,
                    "edgeStgPreRecTime": 5,
                    "edgeStgRecDays": 127,
                    "edgeStgRecMode": 1,
                    "edgeStgRecStartTime": "00:00",
                    "edgeStgRecStopTime": "00:00",
                    "edgeStgRecTime": 60,
                    "edgeStgRetEnabled": False,
                    "edgeStgRetrieveAction": 2,
                    "enableAdvCont": False,
                    "enableAdvLive": False,
                    "enableAutoLiveProfile": False,
                    "enablePtzControl": True,
                    "extDIDev": 0,
                    "extDIPorts": -1,
                    "extraDataSrc": 0,
                    "informationHint": "",
                    "isRemovableLens": False,
                    "pairedSpeakerEnabled": False,
                    "pairedSpeakerId": 0,
                    "profileSettingList": "1,1,1,1,1,1,1,1,1,1,1,1",
                },
                "deviceType": 1,
                "doorbellNum": 0,
                "dsIp": "",
                "dsPort": 7850,
                "enableAdvLive": False,
                "enableAutoLiveProfile": False,
                "enableMulticast": False,
                "enableMulticastMobile": False,
                "enablePtzControl": True,
                "enable_calling_notify": False,
                "enabled": True,
                "exposure_control": 6,
                "exposure_mode": 4,
                "extDIDev": 0,
                "extDIPorts": -1,
                "feRegionList": [],
                "firmware": "",
                "fisheyeDispMode": "",
                "fisheyeParam": {},
                "folder": "/volume1/surveillance/Camera1",
                "forceEnableMulticast": False,
                "fps": 0,
                "hasCamParam": False,
                "host": "192.168.1.101",
                "id": 1,
                "isStatusUnrecognized": False,
                "is_rotated_by_date": True,
                "is_rotated_by_space": False,
                "last_restart_time": "2020-03-27T07:00:07Z",
                "last_sync_time": "2020-03-27T07:00:07Z",
                "ledCap": False,
                "liveBufferingSec": 1,
                "model": "Define",
                "multiDI": False,
                "multicastAudioPort": 0,
                "multicastAudioPortMobile": 0,
                "multicastGrpAddr": "",
                "multicastGrpAddrMobile": "",
                "multicastVideoPort": 0,
                "multicastVideoPortMobile": 0,
                "mute": False,
                "name": "Camera1",
                "objTrack": False,
                "osd_format": 0,
                "osd_position": 6,
                "osd_status": True,
                "ownerDsId": 0,
                "pairedSpeakerEnabled": False,
                "pairedSpeakerId": 0,
                "param_chklist": 0,
                "period_sync_time_hour": 0,
                "port": 554,
                "presetNum": 0,
                "privilege": 31,
                "profileSettingList": "1,1,1,1,1,1,1,1,1,1,1,1",
                "ptzCap": 0,
                "ptzContinuous": 0,
                "ptzDirection": 0,
                "quality": "",
                "recBitrateCtrl": 0,
                "recCbrBitrate": 1000,
                "recStatus": 1,
                "relayPortList": [],
                "resolution": "1920x1080",
                "restart_day": 0,
                "rotation_by_date": 30,
                "rotation_by_space": "10",
                "rotation_option": 0,
                "rtspPathTimeout": 0,
                "setDICap": False,
                "setDOCap": False,
                "singleStream": False,
                "snapshot_path": "/webapi/entry.cgi?api=SYNO.SurveillanceStation.Camera&method=GetSnapshot&version=1&cameraId=1&timestamp=1592532741&preview=true",
                "speedDryCap": False,
                "status": 0,
                "status_flags": 0,
                "stmFisheyeType": 0,
                "stm_info": [
                    {
                        "camPath": "camPath",
                        "fps": 0,
                        "quality": "",
                        "resolution": "1920x1080",
                        "stmNo": 1,
                        "type": 0,
                    },
                    {
                        "camPath": "camPath",
                        "fps": 0,
                        "quality": "",
                        "resolution": "1920x1080",
                        "stmNo": 1,
                        "type": 1,
                    },
                    {
                        "camPath": "camPath",
                        "fps": 0,
                        "quality": "",
                        "resolution": "1920x1080",
                        "stmNo": 1,
                        "type": 2,
                    },
                ],
                "time_server": "",
                "tvStandard": 0,
                "type": 3,
                "uiStmNoList": "1,1,1",
                "update_time": 14630,
                "vendor": "User",
                "videoCapList": [
                    {"stList": ["RTSP"], "vt": "H.264"},
                    {"stList": ["RTSP"], "vt": "MPEG4"},
                    {"stList": ["HTTP"], "vt": "MJPEG"},
                    {"stList": ["RTSP"], "vt": "H.265"},
                    {"stList": ["RTSP"], "vt": "H.264+"},
                    {"stList": ["RTSP"], "vt": "H.265+"},
                ],
                "videoMode": "",
                "video_flip": True,
                "video_mirror": True,
                "video_rotation": 0,
                "volume": 50,
                "volume_space": "460.402",
                "wiperCap": False,
            }
        ],
        "delcam": [],
        "existCamMntTypeMap": None,
        "keyTotalCnt": 2,
        "keyUsedCnt": 1,
        "timestamp": "1592532741",
        "total": 1,
    },
    "success": True,
}

DSM_6_SURVEILLANCE_STATION_CAMERA_EVENT_MOTION_ENUM = {
    "data": {
        "DVAParam": None,
        "MDParam": {
            "camRoi": {"channel": "", "type": 0},
            "enhanceMDWithPD": {"value": False},
            "history": {
                "camCap": False,
                "maxValue": 99,
                "minValue": 1,
                "ssCap": False,
                "value": 90,
            },
            "keep": True,
            "mode": 0,
            "objectSize": {
                "camCap": False,
                "maxValue": 99,
                "minValue": 1,
                "ssCap": False,
                "value": 50,
            },
            "percentage": {
                "camCap": False,
                "maxValue": 99,
                "minValue": 1,
                "ssCap": False,
                "value": 50,
            },
            "region": "000000000000000000000000000000000000000001111111111111111111111111111111111111100111111111111111111111111111111111111110011111111111111111111111111111111111111001111111111111111111111111111111111111100111111111111111111111111111111111111110011111111111111111111111111111111111111001111111111111111111111111111111111111100111111111111111111111111111111111111110011111111111111111111111111111111111111001111111111111111111111111111111111111100111111111111111111111111111111111111110011111111111111111111111111111111111111001111111111111111111111111111111111111100111111111111111111111111111111111111110011111111111111111111111111111111111111001111111111111111111111111111111111111100111111111111111111111111111111111111110011111111111111111111111111111111111111001111111111111111111111111111111111111100111111111111111111111111111111111111110011111111111111111111111111111111111111001111111111111111111111111111111111111100111111111111111111111111111111111111110011111111111111111111111111111111111111001111111111111111111111111111111111111100111111111111111111111111111111111111110011111111111111111111111111111111111111001111111111111111111111111111111111111100000000000000000000000000000000000000000",
            "relatedEvents": [],
            "sensitivity": {
                "camCap": False,
                "maxValue": 99,
                "minValue": 1,
                "ssCap": True,
                "value": 90,
            },
            "shortLiveSecond": {"camCap": False, "ssCap": True, "value": 0},
            "source": 1,
            "threshold": {
                "camCap": False,
                "maxValue": 99,
                "minValue": 1,
                "ssCap": True,
                "value": 10,
            },
        },
        "PDParam": {
            "keep": True,
            "sensitivity": {"cap": False, "maxValue": 0, "minValue": 0, "value": 0},
            "source": -1,
            "triggerMotion": False,
        },
    },
    "success": True,
}

DSM_6_SURVEILLANCE_STATION_CAMERA_EVENT_MD_PARAM_SAVE = {
    "data": {"camId": 1},
    "success": True,
}

DSM_6_SURVEILLANCE_STATION_CAMERA_GET_LIVE_VIEW_PATH = {
    "data": [
        {
            "id": 1,
            "mjpegHttpPath": 'http://192.168.1.100:5000/webapi/entry.cgi?api=SYNO.SurveillanceStation.Stream.VideoStreaming&version=1&method=Stream&format=mjpeg&cameraId=1&StmKey="stmkey1234567890"',
            "multicstPath": "rtsp://syno:stmkey1234567890@192.168.1.100:554/Sms=1.multicast",
            "mxpegHttpPath": 'http://192.168.1.100:5000/webapi/entry.cgi?api=SYNO.SurveillanceStation.Stream.VideoStreaming&version=1&method=Stream&format=mxpeg&cameraId=1&StmKey="stmkey1234567890"',
            "rtspOverHttpPath": "rtsp://192.168.1.100:5000/webman/3rdparty/SurveillanceStation/cgi/rtsp.cgi?Sms=1.unicast&DsId=0&StmKey=stmkey1234567890",
            "rtspPath": "rtsp://syno:stmkey1234567890@192.168.1.100:554/Sms=1.unicast",
        }
    ],
    "success": True,
}

DSM_6_SURVEILLANCE_STATION_CAMERA_ENABLE = {"success": True}

DSM_6_SURVEILLANCE_STATION_CAMERA_DISABLE = {"success": True}
