"""DSM 6 SYNO.Backup.Task data."""

DSM_6_BACKUP_TASK_LIST = {
    "data": {
        "is_data_restoring": "False",
        "is_downloading": "False",
        "is_lun_restoring": "False",
        "is_restoring": "False",
        "is_snapshot_restoring": "False",
        "task_list": [
            {
                "data_enc": "True",
                "data_type": "data",
                "ext3ShareList": [],
                "name": "Backup2Google",
                "repo_id": 1,
                "state": "backupable",
                "status": "none",
                "target_id": "ds.hbk",
                "target_type": "cloud_image",
                "task_id": 1,
                "transfer_type": "google_drive",
                "type": "cloud_image:google_drive",
            },
            {
                "data_enc": "True",
                "data_type": "data",
                "ext3ShareList": [],
                "name": "Backup2HiDrive",
                "repo_id": 2,
                "state": "backupable",
                "status": "none",
                "target_id": "ds.hbk",
                "target_type": "cloud_image",
                "task_id": 2,
                "transfer_type": "hidrive",
                "type": "cloud_image:hidrive",
            },
            {
                "data_enc": "False",
                "data_type": "data",
                "ext3ShareList": [],
                "name": "Backup2USB",
                "repo_id": 3,
                "state": "backupable",
                "status": "none",
                "target_id": "diskstation",
                "target_type": "share",
                "task_id": 3,
                "transfer_type": "local",
                "type": "share:local",
            },
        ],
        "total": 3,
    }
}

DSM_6_BACKUP_TASK_GETS = {
    1: {
        "data": {
            "data_enc": "True",
            "data_type": "data",
            "ext3ShareList": [],
            "name": "Backup2Google",
            "repo_id": 1,
            "source": {
                "app_config": [],
                "app_list": ["Calendar", "CardDAVServer"],
                "app_name_list": ["Synology Calendar", "CardDAV Server"],
                "backup_filter": {"exclude_list": [], "whitelist": []},
                "backup_volumes": [],
                "file_list": [
                    {
                        "dataEncryped": "False",
                        "encryptedShare": "False",
                        "fileSystem": "EXT4",
                        "fileSystemType": "internal",
                        "folderPath": "/homes/admin",
                        "fullPath": "/volume1/homes/admin",
                        "isValidSource": "True",
                        "missing": "False",
                    }
                ],
                "folder_list": [
                    {
                        "dataEncryped": "False",
                        "encryptedShare": "False",
                        "fileSystem": "EXT4",
                        "fileSystemType": "internal",
                        "folderPath": "/homes/admin",
                        "fullPath": "/volume1/homes/admin",
                        "isValidSource": "True",
                        "missing": "False",
                    }
                ],
                "share_list": {
                    "homes": {
                        "dataEncryped": "False",
                        "encryptedShare": "False",
                        "fileSystem": "EXT4",
                        "fileSystemType": "internal",
                        "fullPath": "/volume1/homes",
                        "isValidSource": "True",
                    }
                },
            },
            "state": "backupable",
            "status": "none",
            "target_id": "ds.hbk",
            "target_type": "cloud_image",
            "task_id": 1,
            "transfer_type": "google_drive",
            "type": "cloud_image:google_drive",
        },
        "success": "True",
    },
    2: {
        "data": {
            "data_enc": "True",
            "data_type": "data",
            "ext3ShareList": [],
            "name": "Backup2HiDrive",
            "repo_id": 2,
            "source": {
                "app_config": [],
                "app_list": [
                    "CardDAVServer",
                    "HyperBackup",
                    "HyperBackupVault",
                    "PhotoStation",
                    "Calendar",
                    "MailServer",
                    "WebStation",
                    "WebDAVServer",
                ],
                "app_name_list": [
                    "CardDAV Server",
                    "Hyper Backup",
                    "Hyper Backup Vault",
                    "Photo Station",
                    "Synology Calendar",
                    "Synology Mail Server",
                    "Web Station",
                    "WebDAV Server",
                ],
                "backup_filter": {"exclude_list": [], "whitelist": []},
                "backup_volumes": [],
                "file_list": [
                    {
                        "dataEncryped": "False",
                        "encryptedShare": "False",
                        "fileSystem": "EXT4",
                        "fileSystemType": "internal",
                        "folderPath": "/homes/admin/.Maildir",
                        "fullPath": "/volume1/homes/admin/.Maildir",
                        "isValidSource": "True",
                        "missing": "False",
                    }
                ],
                "folder_list": [
                    {
                        "dataEncryped": "False",
                        "encryptedShare": "False",
                        "fileSystem": "EXT4",
                        "fileSystemType": "internal",
                        "folderPath": "/homes/admin/.Maildir",
                        "fullPath": "/volume1/homes/admin/.Maildir",
                        "isValidSource": "True",
                        "missing": "False",
                    }
                ],
                "share_list": {
                    "homes": {
                        "dataEncryped": "False",
                        "encryptedShare": "False",
                        "fileSystem": "EXT4",
                        "fileSystemType": "internal",
                        "fullPath": "/volume1/homes",
                        "isValidSource": "True",
                    }
                },
            },
            "state": "backupable",
            "status": "none",
            "target_id": "ds.hbk",
            "target_type": "cloud_image",
            "task_id": 2,
            "transfer_type": "hidrive",
            "type": "cloud_image:hidrive",
        }
    },
    3: {
        "data": {
            "data_enc": "False",
            "data_type": "data",
            "ext3ShareList": [],
            "name": "Backup2USB",
            "repo_id": 3,
            "source": {
                "app_config": [],
                "app_list": [
                    "Calendar",
                    "CardDAVServer",
                    "MailServer",
                    "WebStation",
                    "WebDAVServer",
                ],
                "app_name_list": [
                    "Synology Calendar",
                    "CardDAV Server",
                    "Synology Mail Server",
                    "Web Station",
                    "WebDAV Server",
                ],
                "backup_filter": {"exclude_list": [], "whitelist": []},
                "backup_volumes": [],
                "file_list": [
                    {
                        "dataEncryped": "False",
                        "encryptedShare": "False",
                        "fileSystem": "EXT4",
                        "fileSystemType": "internal",
                        "folderPath": "/homes",
                        "fullPath": "/volume1/homes",
                        "isValidSource": "True",
                        "missing": "False",
                    },
                    {
                        "dataEncryped": "False",
                        "encryptedShare": "False",
                        "fileSystem": "EXT4",
                        "fileSystemType": "internal",
                        "folderPath": "/music",
                        "fullPath": "/volume1/music",
                        "isValidSource": "True",
                        "missing": "False",
                    },
                    {
                        "dataEncryped": "False",
                        "encryptedShare": "False",
                        "fileSystem": "EXT4",
                        "fileSystemType": "internal",
                        "folderPath": "/photo",
                        "fullPath": "/volume1/photo",
                        "isValidSource": "True",
                        "missing": "False",
                    },
                    {
                        "dataEncryped": "False",
                        "encryptedShare": "False",
                        "fileSystem": "EXT4",
                        "fileSystemType": "internal",
                        "folderPath": "/video",
                        "fullPath": "/volume1/video",
                        "isValidSource": "True",
                        "missing": "False",
                    },
                    {
                        "dataEncryped": "False",
                        "encryptedShare": "False",
                        "fileSystem": "EXT4",
                        "fileSystemType": "internal",
                        "folderPath": "/web",
                        "fullPath": "/volume1/web",
                        "isValidSource": "True",
                        "missing": "False",
                    },
                ],
                "folder_list": [
                    {
                        "dataEncryped": "False",
                        "encryptedShare": "False",
                        "fileSystem": "EXT4",
                        "fileSystemType": "internal",
                        "folderPath": "/homes",
                        "fullPath": "/volume1/homes",
                        "isValidSource": "True",
                        "missing": "False",
                    },
                    {
                        "dataEncryped": "False",
                        "encryptedShare": "False",
                        "fileSystem": "EXT4",
                        "fileSystemType": "internal",
                        "folderPath": "/music",
                        "fullPath": "/volume1/music",
                        "isValidSource": "True",
                        "missing": "False",
                    },
                    {
                        "dataEncryped": "False",
                        "encryptedShare": "False",
                        "fileSystem": "EXT4",
                        "fileSystemType": "internal",
                        "folderPath": "/photo",
                        "fullPath": "/volume1/photo",
                        "isValidSource": "True",
                        "missing": "False",
                    },
                    {
                        "dataEncryped": "False",
                        "encryptedShare": "False",
                        "fileSystem": "EXT4",
                        "fileSystemType": "internal",
                        "folderPath": "/video",
                        "fullPath": "/volume1/video",
                        "isValidSource": "True",
                        "missing": "False",
                    },
                    {
                        "dataEncryped": "False",
                        "encryptedShare": "False",
                        "fileSystem": "EXT4",
                        "fileSystemType": "internal",
                        "folderPath": "/web",
                        "fullPath": "/volume1/web",
                        "isValidSource": "True",
                        "missing": "False",
                    },
                ],
                "share_list": {
                    "homes": {
                        "dataEncryped": "False",
                        "encryptedShare": "False",
                        "fileSystem": "EXT4",
                        "fileSystemType": "internal",
                        "fullPath": "/volume1/homes",
                        "isValidSource": "True",
                    },
                    "music": {
                        "dataEncryped": "False",
                        "encryptedShare": "False",
                        "fileSystem": "EXT4",
                        "fileSystemType": "internal",
                        "fullPath": "/volume1/music",
                        "isValidSource": "True",
                    },
                    "photo": {
                        "dataEncryped": "False",
                        "encryptedShare": "False",
                        "fileSystem": "EXT4",
                        "fileSystemType": "internal",
                        "fullPath": "/volume1/photo",
                        "isValidSource": "True",
                    },
                    "video": {
                        "dataEncryped": "False",
                        "encryptedShare": "False",
                        "fileSystem": "EXT4",
                        "fileSystemType": "internal",
                        "fullPath": "/volume1/video",
                        "isValidSource": "True",
                    },
                    "web": {
                        "dataEncryped": "False",
                        "encryptedShare": "False",
                        "fileSystem": "EXT4",
                        "fileSystemType": "internal",
                        "fullPath": "/volume1/web",
                        "isValidSource": "True",
                    },
                },
            },
            "state": "backupable",
            "status": "none",
            "target_id": "diskstation",
            "target_type": "share",
            "task_id": 3,
            "transfer_type": "local",
            "type": "share:local",
        },
        "success": "True",
    },
}
